[SKY30-223] Make links within info buttons/tooltips clickable
Vizzuality/skytruth-30x30 pull request #157
Opened 2024-02-02 11:18 UTC by SARodrigues

### Overview

TODO

### Testing instructions

TODO

### Feature relevant tickets

[SKY30-223](https://vizzuality.atlassian.net/browse/SKY30-223)

2024-02-05 08:09 UTC, andresgnlez commented
@SARodrigues the implementation looks good. I am worried about the fact the library is in _alpha_ and has not been updated in 5 years.. The [original library](https://github.com/markdown-it/linkify-it) is maintained though.

Also, we are missing text links (just displaying raw links) and no styling to make the links more prominent. Can you at least add underline styling (or whatever we have in design) to the links, please?

2024-02-05 08:10 UTC, andresgnlez requested changes
@SARodrigues the implementation looks good. I am worried about the fact the library is in alpha and has not been updated in 5 years.. The [original library](https://github.com/markdown-it/linkify-it) is maintained though.

Also, we are missing text links (just displaying raw links) and no styling to make the links more prominent. Can you at least add underline styling (or whatever we have in design) to the links, please?

2024-02-05 13:55 UTC, SARodrigues commented
> @SARodrigues the implementation looks good. I am worried about the fact the library is in alpha and has not been updated in 5 years.. The [original library](https://github.com/markdown-it/linkify-it) is maintained though.

That caught my eye as well when looking for easy to use libraries, but I'm not sure whether going with `linkify-it` would be worth it here, given the use case and for time purposes. 

Although this one isn't maintained, it has over 200k weekly downloads and fulfills our use case quite well and is extremely simple to use. 

Going with the original would (IMHO) mean spending the time to create a custom component that re-implements functionality that already exists. Right now we'd have at very least to duplicate part of the [string parsing](https://github.com/tasti/react-linkify/blob/master/src/components/Linkify.jsx#L26-L58) functionality in order to support multiple links in the same string coming from Strapi, and in the event we happen to need to support have a need to support multiple child elements we'd need to duplicate [even more functionality](https://github.com/tasti/react-linkify/blob/master/src/components/Linkify.jsx#L60-L70).

What do you think? 

&nbsp;

> Also, we are missing text links (just displaying raw links) and no styling to make the links more prominent. Can you at least add underline styling (or whatever we have in design) to the links, please?

Added an underline to the links; the designs are a bit scarce on this one but I agree we should have it for consistency and user friendliness.

2024-02-06 08:46 UTC, andresgnlez commented
> Going with the original would (IMHO) mean spending the time to create a custom component that re-implements functionality that already exists. Right now we'd have at very least to duplicate part of the [string parsing](https://github.com/tasti/react-linkify/blob/master/src/components/Linkify.jsx#L26-L58) functionality in order to support multiple links in the same string coming from Strapi, and in the event we happen to need to support have a need to support multiple child elements we'd need to duplicate [even more functionality](https://github.com/tasti/react-linkify/blob/master/src/components/Linkify.jsx#L60-L70).

> What do you think?

Yeah, I totally agree, it's not worth it. Let's stick with the wrapper. Worst case scenario is the wrapper is not too spread in the codebase so changing it shouldn't be painful.

2024-02-07 08:53 UTC, merged